# Generated by Django 5.2.1 on 2025-06-19 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playeritem',
            name='equipment_post',
        ),
    ]
