# Generated by Django 5.2.1 on 2025-06-19 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_playeritem_equipment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeritem',
            name='equipment_post',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='装备位置'),
        ),
    ]
