# Generated by Django 5.2.1 on 2025-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_playeritem_equipment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeritem',
            name='max_naijiu',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='naijiu',
            field=models.IntegerField(blank=True, default=100, null=True),
        ),
    ]
