# Generated by Django 5.2.1 on 2025-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_playeritem_max_naijiu_alter_playeritem_naijiu'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='金钱'),
        ),
    ]
