# Generated by Django 5.2.1 on 2025-06-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_player_money'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='npcdroplist',
            options={'verbose_name': 'NPC掉落设置'},
        ),
        migrations.AddField(
            model_name='npcdroplist',
            name='count',
            field=models.IntegerField(default=1, verbose_name='掉落数量'),
        ),
        migrations.AlterField(
            model_name='npcdroplist',
            name='gailv',
            field=models.IntegerField(default=50, verbose_name='掉落概率'),
        ),
    ]
