# Generated by Django 5.2.1 on 2025-06-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_npcdroplist_options_npcdroplist_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='max_exp',
            field=models.PositiveBigIntegerField(default=0, verbose_name='最大经验'),
        ),
    ]
