# Generated by Django 5.2.1 on 2025-06-24 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player_max_exp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, '进行中'), (2, '已完成'), (3, '已放弃'), (4, '未开始')], db_index=True, default=1, verbose_name='任务状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='完成时间')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_tasks', to='game.player', verbose_name='玩家')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerTaskProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.PositiveSmallIntegerField(choices=[(1, '物品'), (2, '怪物'), (3, '对话')])),
                ('target_id', models.PositiveIntegerField()),
                ('current', models.IntegerField(default=0)),
                ('player_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresses', to='game.playertask')),
            ],
            options={
                'verbose_name': '玩家任务进度表',
                'verbose_name_plural': '玩家任务进度表',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='任务名称')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('theme', models.PositiveSmallIntegerField(choices=[(1, '主线任务'), (2, '日常任务'), (3, '副本任务')], db_index=True, verbose_name='任务主题')),
                ('function_type', models.PositiveSmallIntegerField(choices=[(1, '对话任务'), (2, '杀怪任务'), (3, '寻物任务')], db_index=True, verbose_name='任务类型')),
                ('is_droppable', models.BooleanField(default=True, verbose_name='可放弃')),
                ('trigger_conditions', models.JSONField(default=dict, help_text='JSON格式的条件配置', verbose_name='触发条件')),
                ('prev_task_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='前置任务ID')),
                ('accept_dialog', models.TextField(blank=True, verbose_name='接受对话')),
                ('progress_dialog', models.TextField(blank=True, verbose_name='进度对话')),
                ('completion_dialog', models.TextField(blank=True, verbose_name='完成对话')),
                ('rewards', models.JSONField(default={'exp': 10, 'money': 10}, help_text='JSON格式的奖励配置', verbose_name='任务奖励')),
                ('accept_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='available_tasks', to='game.gamenpc', verbose_name='接取NPC')),
                ('map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.gamemap', verbose_name='任务地图')),
                ('submit_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submit_tasks', to='game.gamenpc', verbose_name='提交NPC')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
        migrations.AddField(
            model_name='playertask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_tasks', to='game.task', verbose_name='任务'),
        ),
        migrations.CreateModel(
            name='TaskItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.PositiveSmallIntegerField(choices=[(1, '物品'), (2, '怪物'), (3, '对话')])),
                ('target_id', models.PositiveIntegerField()),
                ('amount', models.IntegerField(default=1)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='game.task')),
            ],
            options={
                'verbose_name': '任务目标表',
                'verbose_name_plural': '任务目标表',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['theme', 'function_type'], name='game_task_theme_0ebeaf_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['accept_npc', 'submit_npc'], name='game_task_accept__709fa2_idx'),
        ),
    ]
