# Generated by Django 5.2.1 on 2025-06-24 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playertask_playertaskprocess_task_playertask_task_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playertask',
            options={'verbose_name': '玩家任务表'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': '游戏任务', 'verbose_name_plural': '任务'},
        ),
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='current',
        ),
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='target_type',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='target_id',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='target_type',
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='item_count',
            field=models.IntegerField(default=0, verbose_name='已有数量'),
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='收集物品'),
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='monster_count',
            field=models.IntegerField(default=0, verbose_name='击杀数量'),
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='monster_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='击杀怪物'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='item_count',
            field=models.IntegerField(default=0, verbose_name='需要数量'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='item_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='收集物品'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='monster_count',
            field=models.IntegerField(default=0, verbose_name='击杀数量'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='monster_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='击杀怪物'),
        ),
    ]
