# Generated by Django 5.2.1 on 2025-06-24 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_alter_playertask_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitem',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='monster_id',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='收集物品'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='monster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamenpc', verbose_name='击杀怪物'),
        ),
    ]
