# Generated by Django 5.2.1 on 2025-06-25 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_remove_taskitem_item_id_remove_taskitem_monster_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='monster_count',
        ),
        migrations.RemoveField(
            model_name='playertaskprocess',
            name='monster_id',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='item_count',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='monster',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='monster_count',
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='current_count',
            field=models.IntegerField(default=0, verbose_name='当前数量'),
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='目标ID'),
        ),
        migrations.AddField(
            model_name='playertaskprocess',
            name='target_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '物品'), (2, '怪物'), (3, '对话')], null=True, verbose_name='目标类型'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='目标ID'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='target_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '物品'), (2, '怪物'), (3, '对话')], null=True, verbose_name='目标类型'),
        ),
    ]
