# Generated by Django 5.2.1 on 2025-06-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_playertaskprocess_item_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gang',
            name='current_count',
            field=models.PositiveIntegerField(default=1, verbose_name='当前人数'),
        ),
        migrations.AlterField(
            model_name='playertask',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成'), (3, '已放弃')], db_index=True, default=1, verbose_name='任务状态'),
        ),
        migrations.AlterField(
            model_name='playertaskprocess',
            name='target_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '对话'), (2, '怪物'), (3, '物品')], null=True, verbose_name='目标类型'),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='target_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '对话'), (2, '怪物'), (3, '物品')], null=True, verbose_name='目标类型'),
        ),
    ]
