# Generated by Django 5.2.1 on 2025-06-27 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_gang_current_count_alter_playertask_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_type', models.PositiveSmallIntegerField(choices=[(1, 'NPC商店'), (2, '游戏商城'), (3, '帮会商店')], db_index=True, default=1, verbose_name='商店类型')),
                ('price', models.PositiveIntegerField(verbose_name='价格')),
                ('currency_type', models.PositiveSmallIntegerField(choices=[(1, '铜币'), (2, '金币'), (3, '帮派资金')], default=1, verbose_name='货币类型')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.item', verbose_name='物品')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.gamenpc', verbose_name='关联NPC')),
            ],
            options={
                'verbose_name': '商店商品',
                'verbose_name_plural': '商店商品管理',
                'indexes': [models.Index(fields=['shop_type', 'npc'], name='game_sellgo_shop_ty_ae410b_idx'), models.Index(fields=['shop_type', 'item'], name='game_sellgo_shop_ty_8cb21e_idx')],
            },
        ),
    ]
