# Generated by Django 5.2.1 on 2025-07-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_sellgoods'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sellgoods',
            options={'verbose_name': '游戏商店'},
        ),
        migrations.AddField(
            model_name='player',
            name='big_money',
            field=models.PositiveIntegerField(default=0, verbose_name='金钱'),
        ),
        migrations.AlterField(
            model_name='player',
            name='money',
            field=models.PositiveIntegerField(default=0, verbose_name='货币'),
        ),
    ]
