# Generated by Django 5.2.1 on 2025-07-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_sellgoods_options_player_big_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='douqi',
            field=models.IntegerField(default=1000, verbose_name='斗气'),
        ),
    ]
